//TODO PRIMEIRO SEPARAR AS CLASSES DO HTML EM JSX SEPARADAS 

//TODO LEMBARAR DE DAR OS COMMITS 

// TODO DEPOIS VERIFRICAR A CONSTRUÇÃO DE CADA CLASSE DO INSTRAGRAM 

//TODO LEMBARAR DE DAR OS COMMITS 

//TODO NÃO ESQUECER OS DATAS SETS VER NO NOTION 

//TODO LEMBARAR DE DAR OS COMMITS 

alert ("Olá mundo! via react!");

let  nome= prompt("digite o seu nome");

alert (`OLÁ ${nome}`);